"use client";

import {
  // Whitelist: iconos comunes para presentaciones (extensible)
  Star,
  Heart,
  Check,
  X,
  Plus,
  Minus,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  TrendingUp,
  TrendingDown,
  Target,
  Award,
  Users,
  User,
  Building2,
  Globe,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Zap,
  Lightbulb,
  Rocket,
  Sparkles,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Eye,
  Lock,
  Unlock,
  Shield,
  Activity,
  BarChart3,
  PieChart,
  LineChart,
  Cpu,
  Database,
  Cloud,
  Wifi,
  Smartphone,
  Laptop,
  Monitor,
  Camera,
  Image as ImageLucide,
  Video as VideoLucide,
  Music,
  FileText,
  Folder,
  Download,
  Upload,
  Search,
  Settings,
  Wrench,
  Hammer,
  Briefcase,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Euro,
  PercentSquare,
  Flag,
  type LucideIcon,
} from "lucide-react";
import type { SlideElement } from "@/lib/schema/slide";

const ICONS: Record<string, LucideIcon> = {
  star: Star,
  heart: Heart,
  check: Check,
  x: X,
  plus: Plus,
  minus: Minus,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  target: Target,
  award: Award,
  users: Users,
  user: User,
  building: Building2,
  globe: Globe,
  mail: Mail,
  phone: Phone,
  "map-pin": MapPin,
  calendar: Calendar,
  clock: Clock,
  zap: Zap,
  lightbulb: Lightbulb,
  rocket: Rocket,
  sparkles: Sparkles,
  "check-circle": CheckCircle2,
  "x-circle": XCircle,
  "alert-triangle": AlertTriangle,
  info: Info,
  "help-circle": HelpCircle,
  eye: Eye,
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  activity: Activity,
  "bar-chart": BarChart3,
  "pie-chart": PieChart,
  "line-chart": LineChart,
  cpu: Cpu,
  database: Database,
  cloud: Cloud,
  wifi: Wifi,
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  camera: Camera,
  image: ImageLucide,
  video: VideoLucide,
  music: Music,
  "file-text": FileText,
  folder: Folder,
  download: Download,
  upload: Upload,
  search: Search,
  settings: Settings,
  wrench: Wrench,
  hammer: Hammer,
  briefcase: Briefcase,
  "shopping-cart": ShoppingCart,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  euro: Euro,
  percent: PercentSquare,
  flag: Flag,
};

export const ICON_NAMES = Object.keys(ICONS);

export function IconView({
  el,
}: {
  el: Extract<SlideElement, { type: "icon" }>;
}) {
  const Icon = ICONS[el.iconName] ?? Star;
  const size = Math.min(el.bbox.w, el.bbox.h);
  return (
    <div className="w-full h-full flex items-center justify-center">
      <Icon
        size={size}
        color={el.color}
        strokeWidth={el.strokeWidth}
        absoluteStrokeWidth
      />
    </div>
  );
}
